In [1]:
def sumofnumbers(a,b):
    return a+b

sumofnumbers(2,3)

5

In [8]:
import numpy as np
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
v = np.array([1,2,3])
rank_matrix = np.linalg.matrix_rank(M)
shape_matrix = np.shape(M)
print("Rank of matrix: ", rank_matrix)
print("Shape of matrix: ", shape_matrix)

Rank of matrix:  2
Shape of matrix:  (3, 3)


In [14]:
import numpy as np

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M_1 = M+3
print(M_1)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
import numpy as np

M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([1, 2, 3])
M_transpose = M.T
v_transpose = v.transpose()
print("Transpose matrix:\n ",M_transpose)

print("Transpose vexter:" , v_transpose)

Transpose matrix:
  [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose vexter: [1 2 3]


In [32]:
import math
import numpy as np
x = (2, 7)
# norm = math.sqrt(sum(i**2 for i in x))
# print("The normalized vector x is: ", norm)


# ---------------------------
norm_x = np.linalg.norm(x)
y = x / norm_x
norm_y = np.linalg.norm(y)
print("Norm of x: ", norm_x)
print("Norm of y: ", norm_y)

Norm of x:  7.280109889280518
Norm of y:  1.0


In [41]:
import numpy as np
a = np.array([10,15])
b = np.array([8,2])
c = np.array([1,2,3])
a+b
a-b
a-c

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [42]:
a = np.array([10, 15])
b = np.array([8, 2])
c = np.dot(a, b)
print("The dot product of a and b is:", c)

The dot product of a and b is: 110


In [62]:
matrix_A = np.array([[2,4,9],[3,6,7]])
# a
rank_of_matrix = np.linalg.matrix_rank(matrix_A)
shape_of_matrix = np.shape(matrix_A)
print("Rank of matrix A is: ", rank_of_matrix)
print("Shape of matrix A is: ", shape_of_matrix)
# b
c = matrix_A[1,2]
print(c)
# c
second_column = matrix_A[1:]
print(second_column)

Rank of matrix A is:  2
Shape of matrix A is:  (2, 3)
7
[[3 6 7]]


In [149]:
random_matrix = np.random.randint(-10, 10, size = (3,3))
# random_matrix = np.random.uniform(-10,10,(3,3))
print(random_matrix)

[[ 9 -1  6]
 [-6  1  8]
 [ 0  0 -2]]


In [152]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [168]:
random_matrix = np.random.randint(1, 10, size=(3, 3))
print(random_matrix)
c = np.trace(random_matrix)
print("Trace of the matrix (using for command): ", c)
trace = 0
for i in range(3):
    trace += random_matrix[i][i]
print("Trace of the matrix (using for loops): ", trace)

[[6 7 3]
 [9 2 6]
 [2 2 9]]
Trace of the matrix (using for command):  17
Trace of the matrix (using for loops):  17


In [173]:
values = [1, 2, 3]
diag_matrix = np.diag(values)
final_matrix = diag_matrix.reshape(3, 3)

print(final_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
